version: "3.7"
networks:
  frontend:
    external: true
  backend:
    external: false
  mysql:
    external: true
volumes:
  api_data:
services:
  backend:
    restart: always
    image: registry.sireto.io/deltalender/delta-pdf-api:${COMMIT_SHA}
    build:
      context: ./delta-pdf-api
      dockerfile: Dockerfile
    networks:
      - frontend
      - backend
      - mysql
    volumes:
      - api_data:/opt/deltapdf
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}

      # Database details
      DB_DIR: /opt/deltapdf
      DB_PROVIDER: ${DB_PROVIDER}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DEPLOYMENT: STAGING

      ## JWT secrets
      JWT_SECRET_KEY : ${JWT_SECRET_KEY}
      JWT_ALGORITHM : ${JWT_ALGORITHM}
      JWT_ACCESS_TOKEN_EXPIRE_MINUTES : ${JWT_ACCESS_TOKEN_EXPIRE_MINUTES}

      CARDANO_TRANSACTION_URL : ${CARDANO_TRANSACTION_URL}
      CARDANO_TRANSACTION_SECRET : ${CARDANO_TRANSACTION_SECRET}

      # Email service
      EMAIL_SMTP_SERVER : ${EMAIL_SMTP_SERVER}
      EMAIL_SMTP_PORT : ${EMAIL_SMTP_PORT}
      EMAIL_USERNAME : ${EMAIL_USERNAME}
      EMAIL_PASSWORD : ${EMAIL_PASSWORD}

      # TOTP
      OTP_VALIDITY : ${OTP_VALIDITY}

      # AWS
      AWS_ENDPOINT_URL : ${AWS_ENDPOINT_URL}
      AWS_ACCESS_KEY : ${AWS_ACCESS_KEY}
      AWS_SECRET_KEY : ${AWS_SECRET_KEY}
      AWS_BUCKET : ${AWS_BUCKET}


    deploy:
      restart_policy:
        delay: 30s
      resources:
        limits:
          memory: 3G
      placement:
        constraints:
            - "node.labels.deltalender==true"