import type { Metadata } from "next";
import "./globals.css";
import Layout from "@/shared/layout/_layout";
import ReduxProvider from "@/shared/store/provider/redux-provider";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="enn no-scrollbar">
      <head>
        <link
          rel="preload"
          href="/fonts/Madeva Suarte Signature Font.ttf"
          as="font"
          type="font/tff"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`no-scrollbar antialiased`}>
        <ReduxProvider>
          <Suspense>
            <Layout>{children}</Layout>
          </Suspense>
        </ReduxProvider>
      </body>
    </html>
  );
}
